### ISSUE TITLE
unable to execute multiple statement sql

### ISSUE THREAD

**Issue by wildthink** [feistydog/FeistyDB#10]
It appears the sqlite_prepare_statement only parses the first SQL statement. You need to expose the sqlite_exec to handle a "bulk" load SQL.

**Comment by sbooth** [comment]
`sqlite_exec` returns all of the result rows as text values along with the column names. Also, each result row may have different numbers of columns. What would you expect/like an API like that to look like? One that accepts a closure taking `[String:String]` for each row?

**Comment by wildthink** [comment]
I was just looking for an API to run multiple semicolon delimited statements. Honestly, I had to go back and look at the def (https://www.sqlite.org/c3ref/exec.html) to see that getting the results from each statement was an option. I just ran into some difficulty when running a multi-statement file or string to simply ingest a sql file.

A side note, I was able to figure out how to include a custom sqlite3.c along with the swift into a single Swift Package. I ended up refactoring the layout of the project though.

**Comment by wildthink** [comment]
We can close this if you want. I'm tooling ahead on my fork. I really like the foundation you have here but I do plan on adding a number of conveniences. Bottom line, I'm happy to share/collaborate but I don't want to be nuisance either.

**Comment by sbooth** [comment]
I'm happy to receive any PRs you feel would be a good addition!

Please check out #11 and see if it does what you're after.
