### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by KanybekMomukeyev** [feistydog/FeistyDB#7]
Hello, thanks for sharing source codes:
it would be best,  if you write/compare benchmark tests with raw sqlite,
forex: Insert/Update/Delete 50_000 structs in transaction, also for fetch.

**Comment by KanybekMomukeyev** [comment]
Sorry, found performance tests in source codes

**Comment by sbooth** [comment]
The test suite in general, and performance tests in particular, could use a little attention.
