### ISSUE TITLE
Cocoapods, integrate with iOS platform issue.

### ISSUE THREAD

**Issue by KanybekMomukeyev** [feistydog/FeistyDB#8]
Hi, thanks for sharing source codes! Database performance is great!

1- st issue:

I am trying to integrate FeistyDB to ios platform, and can not solve following issues:
Created new target FeistyDB_iOS platform:

```
 MD5_CTX mdctx; //<-- Use of undeclared identifier 'MD5_CTX'
 unsigned char md_value[MD5_DIGEST_LENGTH]; //<-- Use of undeclared identifier 'MD5_DIGEST_LENGTH'
 MD5_Init(&mdctx);
```

As i realized, we use this functions in uuid.c, so question is here:
is it important to use this extension uuid?

here tests crashed: testUUIDExtension

Have successful builded FeistyDB, without uuid extension to sqlite, is it important to use uuid extension to sqlite?

**Comment by sbooth** [comment]
You can use `FeistyDB` without the UUID extension with no problems. I like to use UUIDs for object IDs but the extension isn't required.

The build problem may be related to CommonCrypto on iOS; I'll take a look.

**Comment by sbooth** [comment]
To ensure `uuid.c` builds on iOS please check that you set the file's compiler flags to match the macOS project.  It needs the flags `-DSQLITE_CORE -DUSE_COMMONCRYPTO` and there are also other flags to customize the sqlite3 build.

**Comment by KanybekMomukeyev** [comment]
@sbooth also i have another question: is there simple way to integrate SQLCipher with FeistyDB.
Did some research, but no idea where to start.

**Comment by sbooth** [comment]
It looks like SQLCipher rolls a custom version of SQLite so I think you would need to change the build process for FeistyDB to compile/use SQLCipher's custom library instead of the standard SQLite in the `sqlite` folder.  I can't really be more specific because I haven't tried.
